commit baabcf4a4daf71a1567b7d60e89ddde7bcac45f8 Author: Jerry Cao <jerry.cao@amlogic.com> Date:   Fri Jun 2 15:27:45 2017 -0700
    Fix GCC 4.7.x compilation error for AXG/TXLX [1/1]

    [Problem]
    GCC 4.7.x will report following error when building AxG/TXLX.

    board/txlx/css_pm.c:102:38: error: variable 'clusterstat' set but not
    used [-Werror=unused-but-set-variable]

    [Solution]
    Remove clusterstat variable as it's not used in single cluster SoC

    [Test]
    AXG/TXLX compilation success with GCC 4.7.2

    Change-Id: I89f18d4d802206317eaa83fa83b981775ef9719a

gxb      build ok
gxtvbb   build ok
gxl      build ok
txl      build ok
txlx     build ok
axg      build ok

Change-Id: If9cb4b0eed29d7ab1e9e916216889945f28e003f